version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - PROD_BASE_URL=${PROD_BASE_URL}
      - LOCAL_BASE_URL=${LOCAL_BASE_URL}
    volumes:
      - .:/app
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
