version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "src/backend/routes/transcript/streamlit_transcription.py"]
    ports:
      - "8051:8051"
