name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11" # Anpassa om nödvändigt

      - name: Install Dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make Startup Script Executable
        run: |
          chmod +x src/startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager" # Rätt namn
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.11/x64 # Matcha version
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11/x64/lib
