name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"  # Specify the Python version you are using

      - name: Install Dependencies
        run: |
          cd src  # Navigate to the src directory
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager"  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          startup-command: "gunicorn --chdir /home/site/wwwroot/src --bind 0.0.0.0:8000 --timeout 600 app:app & streamlit run /home/site/wwwroot/src/backend/routes/transcript/streamlit_transcription.py --server.port 8501"
