name: Deployment To Rule Them All

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"  # Specify a stable Python version

      - name: Install Dependencies
        run: |
          echo "🔄 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "✅ Dependencies installed successfully."

      - name: Verify Python Version
        run: python --version

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager"  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .  # Path to your deployment package (usually your app source)

