name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image to ACR
      run: |
        docker build -t $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:latest .
        docker push $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:latest

    - name: Run deployment script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
