name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13" # Specify a stable Python version

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python Version
        run: python --version

      - name: Verify Deployment Package
        run: |
          if [ ! -f ./src/startup.sh ]; then
            echo "Error: startup.sh is missing!"
            exit 1
          fi
          if [ ! -f ./requirements.txt ]; then
            echo "Error: requirements.txt is missing!"
            exit 1
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./ # Deploy the entire project root to include startup.sh
