name: Deployment To Rule Them All

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"  # Specify a stable Python version

      - name: Delete Temporary Files
        run: |
          echo "🔄 Cleaning up temporary files to free up space..."
          find /tmp -type f -exec rm -f {} + || true
          rm -f /home/site/wwwroot/output.tar.gz || true
          echo "✅ Temporary files cleaned up."

      - name: Install Dependencies
        run: |
          echo "🔄 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "✅ Dependencies installed successfully."

      - name: Verify Python Version
        run: python --version

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager"  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      # Add a step to specify the command to run the Flask and Streamlit apps
      - name: Run the Flask and Streamlit apps
        run: |
          echo "🚀 Starting Flask and Streamlit apps..."
          python src/app.py
