name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ secrets.DOCKER_IMAGE }}:${{ github.sha }} .
          echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io --username ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ secrets.DOCKER_IMAGE }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
