name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -r requirements.txt
          python -m pip install pytest  # Ensure pytest is installed

      - name: Debug Environment (Check Python & pytest installation)
        run: |
          python --version
          which python
          which pytest
          pip list

      - name: Run Tests
        run: python -m pytest  # Use module format to avoid command not found error

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "PodManager"  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
