name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to ACR
      run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest

    - name: Run deployment script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
      env:
        REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
