name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13" # Specify a stable Python version

      - name: Clean Temporary Files
        run: |
          echo "🔄 Cleaning up temporary files to free up space..."
          find /tmp -type f -exec rm -f {} + || true
          rm -f /home/site/wwwroot/output.tar.gz || true
          echo "✅ Temporary files cleaned up."

      - name: Install Dependencies
        run: |
          echo "🔄 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "✅ Dependencies installed successfully."

      - name: Verify Python Version
        run: python --version

      - name: Make startup.sh Executable
        run: chmod +x ./startup.sh

      - name: Clean Up wwwroot Before Deployment
        run: |
          echo "🔄 Cleaning up /wwwroot before deployment..."
          rm -rf /home/site/wwwroot/* || true
          echo "✅ /wwwroot cleaned up before deployment."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./ # Ensure the correct deployment package path
