name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Create Virtual Environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Install Dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Verify Deployment Structure
        run: |
          echo "Verifying deployment structure..."
          ls -l ./src

      - name: Prepare Deployment Package
        run: |
          echo "Preparing deployment package..."
          mkdir -p ./deploy
          cp -r ./src ./deploy/src
          if [ -f .env ]; then
            cp .env ./deploy/.env
          else
            echo "Warning: .env file not found. Skipping..."
          fi
          ls -l ./deploy

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "podmanager" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy # Deploy the prepared package

      - name: Ensure Deployment Package is Extracted
        run: |
          if [ -f /home/site/wwwroot/output.tar.gz ]; then
            echo "Extracting deployment package..."
            tar -xzf /home/site/wwwroot/output.tar.gz -C /home/site/wwwroot
            rm /home/site/wwwroot/output.tar.gz
          else
            echo "No deployment package found to extract."
          fi
